FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/cache-handler

FROM caddy:latest

ARG CADDYFILE=Caddyfile.cache

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY ${CADDYFILE} /etc/caddy/Caddyfile
