name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u phillaf -p ${{ secrets.DOCKERHUB_PASS }}

    - name: Build Docker image
      run: docker build -t phillaf/proflie:latest .

    - name: Publish Docker image
      run: docker push phillaf/proflie

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
